version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
    - "9092:9092"
    - "29092:29092"
    environment:
      KAFKA_LISTENERS: LISTENER_INT://kafka:29092,LISTENER_EXT://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INT://kafka:29092,LISTENER_EXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INT:PLAINTEXT,LISTENER_EXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
    depends_on:
      - zookeeper
  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    command: mongod --auth
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=admindb
      - MONGO_INITDB_ROOT_PASSWORD=admindb
    volumes:
      - /var/lib/boot2docker/mongo-data/:/data/db/
  producer:
    build:
      context: .
      dockerfile: ./producer/Dockerfile.producer
    container_name: producer
    ports:
      - "8081:8081"
    depends_on:
      - kafka
  consumer:
    build:
      context: .
      dockerfile: ./consumer/Dockerfile.consumer
#    container_name: consumer
    depends_on:
      - kafka
      - mongo
  reader:
    build:
      context: .
      dockerfile: ./reader/Dockerfile.reader
    container_name: reader
    ports:
      - "8082:8082"
    depends_on:
      - mongo
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: "1000:1000"
    volumes:
      - /pipeline-config/:/etc/prometheus/
      - /var/lib/boot2docker/prometheus-data:/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    restart: always
  grafana:
    image: grafana/grafana
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    restart: always
