version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
    - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
    - "9092:9092"
    - "29092:29092"
    environment:
      KAFKA_LISTENERS: LISTENER_INT://kafka:29092,LISTENER_EXT://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: LISTENER_INT://kafka:29092,LISTENER_EXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_INT:PLAINTEXT,LISTENER_EXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_INT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    command: mongod --auth
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=admindb
      - MONGO_INITDB_ROOT_PASSWORD=admindb
  producer:
    image: dmihov/pipeline-producer
    container_name: producer
    ports:
      - "8081:8081"
  consumer:
    image: dmihov/pipeline-consumer
    container_name: consumer
  reader:
    image: dmihov/pipeline-reader
    container_name: reader
    ports:
      - "8082:8082"

