scrape_configs:
  - job_name: 'spring-actuator'
    metrics_path: '/pipeline/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.99.100:8081', '192.168.99.100:8082']